This problem was asked by Stripe.

Given an array of integers, find the first missing positive integer in linear time and constant space. In other words, find the lowest positive integer that does not exist in the array. The array can contain duplicates and negative numbers as well.

For example, the input [3, 4, -1, 1] should give 2. The input [1, 2, 0] should give 3.

You can modify the input array in-place.

# Brute force Solution

In [8]:
def lowest_missing(l):
    for i in range(1, len(l) + 1):
        if i not in l:
            return i
    return len(l) + 2

In [9]:
assert lowest_missing([3, 4, -1, 1]) == 2

# Solution in linear time

We can remark that the lowest missing number is always between 1 and n+1 where n is the length of the array. Indeed, if the lowest integer missing was greater than  n+1, it would mean, all the integers between 1 and n+1 are in the array, which is impossible because the array only has n elements.

WLOG, we could assume that the array only contains positive numbers between 1 and n+1. We won't need that for this solution.

Here is a solution that goes through the array only one time. We go through the array. When we encounter a number i between 1 and n+1, we put it at index i-1 (by switching with the number at the index i-1, if this number is not already equal to i).

At the end, we get an array, that looks like [1,2,3, ..] and the first number missing is our lowest missing number.(Because if it was in the original array, it would have been switched to this position).

The space complexity is O(1) because we only have a constant number of variable besides our array that we modify in place. Concerning the time complexity, we go through the whole array once to modify it, and we take an extra step each time we have to make a switch. Since we make at most n switch, our time complexity is O(n)

In [13]:
def lowest_missing_opt(l):
    index = 0
    n = len(l)
    while index < n:
        e = l[index]
        if (0 < e) and (e < n) and (l[e-1] != e):
            l[e-1], l[index] = l[index], l[e-1]
        else:
            index += 1
        print(l)
    for i,j in enumerate(l):
        if i+1 != j:
            return i+1
    else:
        return n+1

In [14]:
assert lowest_missing_opt([3, 4, -1, 1]) == 2

[-1, 4, 3, 1]
[-1, 4, 3, 1]
[-1, 4, 3, 1]
[-1, 4, 3, 1]
[1, 4, 3, -1]
[1, 4, 3, -1]


In [18]:
import numpy as np
l = np.random.randint(0, 10, 10)
print(lowest_missing(l))
assert lowest_missing_opt(l) == lowest_missing(l)

4
[8 1 3 3 9 0 7 3 0 2]
[3 1 3 3 9 0 7 8 0 2]
[3 1 3 3 9 0 7 8 0 2]
[1 3 3 3 9 0 7 8 0 2]
[1 3 3 3 9 0 7 8 0 2]
[1 3 3 3 9 0 7 8 0 2]
[1 3 3 3 9 0 7 8 0 2]
[1 3 3 3 0 0 7 8 9 2]
[1 3 3 3 0 0 7 8 9 2]
[1 3 3 3 0 0 7 8 9 2]
[1 3 3 3 0 0 7 8 9 2]
[1 3 3 3 0 0 7 8 9 2]
[1 3 3 3 0 0 7 8 9 2]
[1 2 3 3 0 0 7 8 9 3]
[1 2 3 3 0 0 7 8 9 3]
